flowchart TD
  classDef section fill:#b6f0a3,stroke:#2d6f2d,stroke-width:2px,color:#000;
  classDef subsection fill:#cfe3ff,stroke:#3060a0,color:#000;
  classDef orphan fill:#eee,stroke:#aaa,color:#666;

  let["Let"]:::orphan
  variables_addition["Variable, Addition"]:::section
  matrices["Matrix"]:::section
  ket_states["Ket (State)"]:::section
  photons_wave_particle_duality["Photon, Wave-particle Duality"]:::section
  superpositions_matrix_addition["Superposition, Matrix Addition"]:::section
  set_theory["Set Theory"]:::section
  functions["Function"]:::section
  summation["Summation"]:::orphan
  trigonometry["Trigonometry"]:::section
  calculus["Calculus"]:::section
  complex_numbers["Complex Number"]:::section
  linear_algebra_i["Linear Algebra I"]:::section
  hilbert_spaces["Hilbert Space"]:::section
  planck_einstein_relation["Planck-Einstein Relation"]:::orphan
  angular_frequency_reduced_planck_constant["Angular Frequency, reduced Planck constant"]:::orphan
  particle_energies["Particle Energy"]:::section
  particle_phases["Particle Phase"]:::section
  schruxf6dingers_equation_hamiltonian["Schrödinger's Equation, Hamiltonian I,"]:::section
  quantum_system["Quantum System"]:::section
  linear_algebra_ii["Linear Algebra II"]:::section
  observables["Observable"]:::section
  pauli_matrices["Pauli Matrices"]:::section
  bloch_sphere["Bloch Sphere"]:::section
  observable_on_a_qubit["Observable on a qubit"]:::section
  degeneracy["Degeneracy"]:::section
  compatibility["Compatibility"]:::section
  probability_theory["Probability Theory"]:::section
  borns_rule["Born's Rule"]:::section
  measuring_a_quantum_state["Measuring a Quantum State"]:::section
  density_matrix["Density Matrix"]:::section
  uncertainty_relation["Uncertainty Relation"]:::section
  linear_algebra_iii["Linear Algebra III"]:::section
  no_cloning_theorem["No-Cloning Theorem"]:::section
  quantum_information_capacity["Quantum Information Capacity"]:::section
  basic_decoding_theory["Basic Decoding Theory"]:::section
  basic_distinguishability_theory["Basic Distinguishability Theory"]:::section
  quantum_cryptography["Quantum Cryptography"]:::section
  quantum_dynamics["Quantum Dynamics"]:::section

  let ~~~ variables_addition
  variables_addition ~~~ matrices
  matrices ~~~ ket_states
  ket_states ~~~ photons_wave_particle_duality
  photons_wave_particle_duality ~~~ superpositions_matrix_addition
  superpositions_matrix_addition ~~~ set_theory
  set_theory ~~~ functions
  functions ~~~ summation
  summation ~~~ trigonometry
  trigonometry ~~~ calculus
  calculus ~~~ complex_numbers
  complex_numbers ~~~ linear_algebra_i
  linear_algebra_i ~~~ hilbert_spaces
  hilbert_spaces ~~~ planck_einstein_relation
  planck_einstein_relation ~~~ angular_frequency_reduced_planck_constant
  angular_frequency_reduced_planck_constant ~~~ particle_energies
  particle_energies ~~~ particle_phases
  particle_phases ~~~ schruxf6dingers_equation_hamiltonian
  schruxf6dingers_equation_hamiltonian ~~~ quantum_system
  quantum_system ~~~ linear_algebra_ii
  linear_algebra_ii ~~~ observables
  observables ~~~ pauli_matrices
  pauli_matrices ~~~ bloch_sphere
  bloch_sphere ~~~ observable_on_a_qubit
  observable_on_a_qubit ~~~ degeneracy
  degeneracy ~~~ compatibility
  compatibility ~~~ probability_theory
  probability_theory ~~~ borns_rule
  borns_rule ~~~ measuring_a_quantum_state
  measuring_a_quantum_state ~~~ density_matrix
  density_matrix ~~~ uncertainty_relation
  uncertainty_relation ~~~ linear_algebra_iii
  linear_algebra_iii ~~~ no_cloning_theorem
  no_cloning_theorem ~~~ quantum_information_capacity
  quantum_information_capacity ~~~ basic_decoding_theory
  basic_decoding_theory ~~~ basic_distinguishability_theory
  basic_distinguishability_theory ~~~ quantum_cryptography
  quantum_cryptography ~~~ quantum_dynamics

  matrices --> variables_addition
  ket_states --> matrices
  photons_wave_particle_duality --> ket_states
  superpositions_matrix_addition --> ket_states
  set_theory --> complex_numbers
  trigonometry --> functions
  complex_numbers --> calculus
  linear_algebra_i --> complex_numbers
  linear_algebra_i --> set_theory
  linear_algebra_i --> ket_states
  linear_algebra_i --> functions
  linear_algebra_i --> hilbert_spaces
  linear_algebra_i --> matrices
  hilbert_spaces --> linear_algebra_i
  hilbert_spaces --> complex_numbers
  particle_energies --> linear_algebra_i
  particle_phases --> complex_numbers
  particle_phases --> quantum_system
  schruxf6dingers_equation_hamiltonian --> particle_energies
  schruxf6dingers_equation_hamiltonian --> particle_phases
  schruxf6dingers_equation_hamiltonian --> linear_algebra_i
  quantum_system --> hilbert_spaces
  quantum_system --> schruxf6dingers_equation_hamiltonian
  linear_algebra_ii --> linear_algebra_i
  linear_algebra_ii --> hilbert_spaces
  linear_algebra_ii --> set_theory
  linear_algebra_ii --> calculus
  linear_algebra_ii --> complex_numbers
  linear_algebra_ii --> observables
  observables --> linear_algebra_ii
  observables --> hilbert_spaces
  pauli_matrices --> linear_algebra_ii
  observable_on_a_qubit --> observables
  observable_on_a_qubit --> bloch_sphere
  degeneracy --> linear_algebra_i
  degeneracy --> linear_algebra_ii
  degeneracy --> schruxf6dingers_equation_hamiltonian
  degeneracy --> hilbert_spaces
  compatibility --> linear_algebra_i
  compatibility --> linear_algebra_ii
  compatibility --> observables
  probability_theory --> set_theory
  probability_theory --> linear_algebra_i
  probability_theory --> linear_algebra_ii
  borns_rule --> quantum_system
  borns_rule --> observables
  borns_rule --> probability_theory
  borns_rule --> linear_algebra_ii
  measuring_a_quantum_state --> observables
  measuring_a_quantum_state --> borns_rule
  measuring_a_quantum_state --> linear_algebra_ii
  measuring_a_quantum_state --> linear_algebra_i
  density_matrix --> linear_algebra_ii
  density_matrix --> observables
  density_matrix --> probability_theory
  uncertainty_relation --> linear_algebra_i
  uncertainty_relation --> borns_rule
  uncertainty_relation --> probability_theory
  uncertainty_relation --> observables
  linear_algebra_iii --> linear_algebra_i
  linear_algebra_iii --> linear_algebra_ii
  no_cloning_theorem --> linear_algebra_iii
  no_cloning_theorem --> linear_algebra_i
  quantum_information_capacity --> quantum_system
  quantum_information_capacity --> hilbert_spaces
  quantum_information_capacity --> linear_algebra_i
  quantum_information_capacity --> borns_rule
  quantum_information_capacity --> linear_algebra_ii
  basic_decoding_theory --> quantum_information_capacity
  basic_decoding_theory --> hilbert_spaces
  basic_distinguishability_theory --> basic_decoding_theory
  quantum_cryptography --> set_theory
  quantum_cryptography --> functions
  quantum_cryptography --> pauli_matrices
  quantum_cryptography --> basic_decoding_theory
  quantum_cryptography --> no_cloning_theorem
  quantum_dynamics --> schruxf6dingers_equation_hamiltonian
  quantum_dynamics --> linear_algebra_i
  quantum_dynamics --> linear_algebra_ii
  quantum_dynamics --> probability_theory
  quantum_dynamics --> hilbert_spaces
  quantum_dynamics --> borns_rule
  quantum_dynamics --> complex_numbers
  quantum_dynamics --> ket_states
  quantum_dynamics --> linear_algebra_iii
  quantum_dynamics --> observables
  quantum_dynamics --> calculus
  quantum_dynamics --> compatibility

  linkStyle 42,49,55,66 stroke:#e74c3c,stroke-width:2px
  linkStyle 38,39,40,41,43,44,45,46,47,48,50,51,52,53,54,56,57,58,59,60,61,62,63,64,65,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125 stroke:#444,stroke-width:1px

%% Sections: 39, edges: 88, out-of-order (downward, red): 4, in-order (upward, gray): 84
